version: "3.7"

services:
  app:
    build:
      context: ./
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    environment:
      - ENVIRONMENT=test
      - PYTHONUNBUFFERED
      - DEBUG
      - PORT
      - AWS_ACCESS_KEY_ID=anything
      - AWS_SECRET_ACCESS_KEY=anything
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - app_network

  dynamodb:
    image: amazon/dynamodb-local
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mailhog:
